print("Welcome to Tip calculator")
x = input("What is the total bill? ")
y = input("How much tip would you like to give? 10, 12, 14?")
z = input("How many people would you like to split the bill between?")
k = int(x)
l = int(y)
m = int(z)
a = int((k+(k*l)/100))
c = int(a/m)
print(c)
